######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 11 19:16:10 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input

HEADERS += net.h
FORMS +=
SOURCES += main.cpp net.cpp
RESOURCES += batfile.qrc
